.PHONY: clean All

All:
	@echo "----------Building project:[ TestElk - Debug ]----------"
	@cd "TestElk" && "$(MAKE)" -f  "TestElk.mk"
clean:
	@echo "----------Cleaning project:[ TestElk - Debug ]----------"
	@cd "TestElk" && "$(MAKE)" -f  "TestElk.mk" clean
