/*----- PROTECTED REGION ID(EarthQuakeGeneratorStateMachine.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        EarthQuakeGeneratorStateMachine.cpp
//
// description : State machine file for the EarthQuakeGenerator class
//
// project :     EarthQuakeGenerator
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
// Matteo Di Carlo INAF
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <EarthQuakeGenerator.h>

/*----- PROTECTED REGION END -----*/	//	EarthQuakeGenerator::EarthQuakeGeneratorStateMachine.cpp

//================================================================
//  States  |  Description
//================================================================


namespace EarthQuakeGenerator_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : EarthQuakeGenerator::is_DateReferenceEvent_allowed()
 *	Description : Execution allowed for DateReferenceEvent attribute
 */
//--------------------------------------------------------
bool EarthQuakeGenerator::is_DateReferenceEvent_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for DateReferenceEvent attribute in read access.
	/*----- PROTECTED REGION ID(EarthQuakeGenerator::DateReferenceEventStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	EarthQuakeGenerator::DateReferenceEventStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : EarthQuakeGenerator::is_Latitude_allowed()
 *	Description : Execution allowed for Latitude attribute
 */
//--------------------------------------------------------
bool EarthQuakeGenerator::is_Latitude_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for Latitude attribute in read access.
	/*----- PROTECTED REGION ID(EarthQuakeGenerator::LatitudeStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	EarthQuakeGenerator::LatitudeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : EarthQuakeGenerator::is_Longitude_allowed()
 *	Description : Execution allowed for Longitude attribute
 */
//--------------------------------------------------------
bool EarthQuakeGenerator::is_Longitude_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for Longitude attribute in read access.
	/*----- PROTECTED REGION ID(EarthQuakeGenerator::LongitudeStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	EarthQuakeGenerator::LongitudeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : EarthQuakeGenerator::is_Depth_allowed()
 *	Description : Execution allowed for Depth attribute
 */
//--------------------------------------------------------
bool EarthQuakeGenerator::is_Depth_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for Depth attribute in read access.
	/*----- PROTECTED REGION ID(EarthQuakeGenerator::DepthStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	EarthQuakeGenerator::DepthStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : EarthQuakeGenerator::is_ReportedMagnitudes_allowed()
 *	Description : Execution allowed for ReportedMagnitudes attribute
 */
//--------------------------------------------------------
bool EarthQuakeGenerator::is_ReportedMagnitudes_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for ReportedMagnitudes attribute in read access.
	/*----- PROTECTED REGION ID(EarthQuakeGenerator::ReportedMagnitudesStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	EarthQuakeGenerator::ReportedMagnitudesStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : EarthQuakeGenerator::is_GeographicaLocation_allowed()
 *	Description : Execution allowed for GeographicaLocation attribute
 */
//--------------------------------------------------------
bool EarthQuakeGenerator::is_GeographicaLocation_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for GeographicaLocation attribute in read access.
	/*----- PROTECTED REGION ID(EarthQuakeGenerator::GeographicaLocationStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	EarthQuakeGenerator::GeographicaLocationStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : EarthQuakeGenerator::is_JsonTrans_allowed()
 *	Description : Execution allowed for JsonTrans attribute
 */
//--------------------------------------------------------
bool EarthQuakeGenerator::is_JsonTrans_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for JsonTrans attribute in read access.
	/*----- PROTECTED REGION ID(EarthQuakeGenerator::JsonTransStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	EarthQuakeGenerator::JsonTransStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : EarthQuakeGenerator::is_NdkFileName_allowed()
 *	Description : Execution allowed for NdkFileName attribute
 */
//--------------------------------------------------------
bool EarthQuakeGenerator::is_NdkFileName_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for NdkFileName attribute in Write access.
	/*----- PROTECTED REGION ID(EarthQuakeGenerator::NdkFileNameStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	EarthQuakeGenerator::NdkFileNameStateAllowed_WRITE

	//	Not any excluded states for NdkFileName attribute in read access.
	/*----- PROTECTED REGION ID(EarthQuakeGenerator::NdkFileNameStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	EarthQuakeGenerator::NdkFileNameStateAllowed_READ
	return true;
}


//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : EarthQuakeGenerator::is_NextEvent_allowed()
 *	Description : Execution allowed for NextEvent attribute
 */
//--------------------------------------------------------
bool EarthQuakeGenerator::is_NextEvent_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for NextEvent command.
	/*----- PROTECTED REGION ID(EarthQuakeGenerator::NextEventStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	EarthQuakeGenerator::NextEventStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : EarthQuakeGenerator::is_Stop_allowed()
 *	Description : Execution allowed for Stop attribute
 */
//--------------------------------------------------------
bool EarthQuakeGenerator::is_Stop_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Stop command.
	/*----- PROTECTED REGION ID(EarthQuakeGenerator::StopStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	EarthQuakeGenerator::StopStateAllowed
	return true;
}


/*----- PROTECTED REGION ID(EarthQuakeGenerator::EarthQuakeGeneratorStateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	EarthQuakeGenerator::EarthQuakeGeneratorStateAllowed.AdditionalMethods

}	//	End of namespace
