/*----- PROTECTED REGION ID(EarthQuakeGenerator.h) ENABLED START -----*/
//=============================================================================
//
// file :        EarthQuakeGenerator.h
//
// description : Include file for the EarthQuakeGenerator class
//
// project :     EarthQuakeGenerator
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
// Matteo Di Carlo INAF
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef EarthQuakeGenerator_H
#define EarthQuakeGenerator_H

#include <tango.h>
#include <sstream>
#include <string>
#include <fstream>

/*----- PROTECTED REGION END -----*/	//	EarthQuakeGenerator.h
#include "json/json.hpp"
using json = nlohmann::json;
/**
 *  EarthQuakeGenerator class description:
 *    EarthQuakeGenerator
 */

namespace EarthQuakeGenerator_ns
{
/*----- PROTECTED REGION ID(EarthQuakeGenerator::Additional Class Declarations) ENABLED START -----*/

//	Additional Class Declarations

/*----- PROTECTED REGION END -----*/	//	EarthQuakeGenerator::Additional Class Declarations

class EarthQuakeGenerator : public TANGO_BASE_CLASS
{

/*----- PROTECTED REGION ID(EarthQuakeGenerator::Data Members) ENABLED START -----*/

//	Add your own data members
private:
    vector<string> *allEventInformation;

/*----- PROTECTED REGION END -----*/	//	EarthQuakeGenerator::Data Members


//	Attribute data members
public:
	Tango::DevString	*attr_DateReferenceEvent_read;
	Tango::DevDouble	*attr_Latitude_read;
	Tango::DevDouble	*attr_Longitude_read;
	Tango::DevDouble	*attr_Depth_read;
	Tango::DevString	*attr_ReportedMagnitudes_read;
	Tango::DevString	*attr_GeographicaLocation_read;
	Tango::DevString	*attr_JsonTrans_read;
	Tango::DevString	*attr_NdkFileName_read;
	Tango::DevString	*attr_archiveValue_read;

//	Constructors and destructors
public:
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	EarthQuakeGenerator(Tango::DeviceClass *cl,string &s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	EarthQuakeGenerator(Tango::DeviceClass *cl,const char *s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device name
	 *	@param d	Device description.
	 */
	EarthQuakeGenerator(Tango::DeviceClass *cl,const char *s,const char *d);
	/**
	 * The device object destructor.
	 */
	~EarthQuakeGenerator() {delete_device();};


//	Miscellaneous methods
public:
	/*
	 *	will be called at device destruction or at init command.
	 */
	void delete_device();
	/*
	 *	Initialize the device
	 */
	virtual void init_device();
	/*
	 *	Always executed method before execution command method.
	 */
	virtual void always_executed_hook();


//	Attribute methods
public:
	//--------------------------------------------------------
	/*
	 *	Method      : EarthQuakeGenerator::read_attr_hardware()
	 *	Description : Hardware acquisition for attributes.
	 */
	//--------------------------------------------------------
	virtual void read_attr_hardware(vector<long> &attr_list);
	//--------------------------------------------------------
	/*
	 *	Method      : EarthQuakeGenerator::write_attr_hardware()
	 *	Description : Hardware writing for attributes.
	 */
	//--------------------------------------------------------
	virtual void write_attr_hardware(vector<long> &attr_list);

/**
 *	Attribute DateReferenceEvent related methods
 *	Description: 
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
	virtual void read_DateReferenceEvent(Tango::Attribute &attr);
	virtual bool is_DateReferenceEvent_allowed(Tango::AttReqType type);
/**
 *	Attribute Latitude related methods
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_Latitude(Tango::Attribute &attr);
	virtual bool is_Latitude_allowed(Tango::AttReqType type);
/**
 *	Attribute Longitude related methods
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_Longitude(Tango::Attribute &attr);
	virtual bool is_Longitude_allowed(Tango::AttReqType type);
/**
 *	Attribute Depth related methods
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_Depth(Tango::Attribute &attr);
	virtual bool is_Depth_allowed(Tango::AttReqType type);
/**
 *	Attribute ReportedMagnitudes related methods
 *	Description: 
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
	virtual void read_ReportedMagnitudes(Tango::Attribute &attr);
	virtual bool is_ReportedMagnitudes_allowed(Tango::AttReqType type);
/**
 *	Attribute GeographicaLocation related methods
 *	Description: 
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
	virtual void read_GeographicaLocation(Tango::Attribute &attr);
	virtual bool is_GeographicaLocation_allowed(Tango::AttReqType type);
/**
 *	Attribute JsonTrans related methods
 *	Description: 
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
	virtual void read_JsonTrans(Tango::Attribute &attr);
	virtual bool is_JsonTrans_allowed(Tango::AttReqType type);
/**
 *	Attribute NdkFileName related methods
 *	Description: 
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
	virtual void read_NdkFileName(Tango::Attribute &attr);
	virtual void write_NdkFileName(Tango::WAttribute &attr);
	virtual bool is_NdkFileName_allowed(Tango::AttReqType type);
/**
 *	Attribute archiveValue related methods
 *	Description: 
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
	virtual void read_archiveValue(Tango::Attribute &attr);
	virtual bool is_archiveValue_allowed(Tango::AttReqType type);


	//--------------------------------------------------------
	/**
	 *	Method      : EarthQuakeGenerator::add_dynamic_attributes()
	 *	Description : Add dynamic attributes if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_attributes();




//	Command related methods
public:
	/**
	 *	Command NextEvent related method
	 *	Description: 
	 *
	 */
	virtual void next_event();
	virtual bool is_NextEvent_allowed(const CORBA::Any &any);
	/**
	 *	Command Stop related method
	 *	Description: 
	 *
	 */
	virtual void stop();
	virtual bool is_Stop_allowed(const CORBA::Any &any);


	//--------------------------------------------------------
	/**
	 *	Method      : EarthQuakeGenerator::add_dynamic_commands()
	 *	Description : Add dynamic commands if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_commands();

/*----- PROTECTED REGION ID(EarthQuakeGenerator::Additional Method prototypes) ENABLED START -----*/

//	Additional Method prototypes


/*----- PROTECTED REGION END -----*/	//	EarthQuakeGenerator::Additional Method prototypes
};

/*----- PROTECTED REGION ID(EarthQuakeGenerator::Additional Classes Definitions) ENABLED START -----*/

//	Additional Classes Definitions

/*----- PROTECTED REGION END -----*/	//	EarthQuakeGenerator::Additional Classes Definitions

}	//	End of namespace

#endif   //	EarthQuakeGenerator_H
