/*----- PROTECTED REGION ID(EarthQuakeGeneratorClass.cpp) ENABLED START -----*/
static const char *RcsId      = "$Id:  $";
static const char *TagName    = "$Name:  $";
static const char *CvsPath    = "$Source:  $";
static const char *SvnPath    = "$HeadURL:  $";
static const char *HttpServer = "http://www.esrf.eu/computing/cs/tango/tango_doc/ds_doc/";
//=============================================================================
//
// file :        EarthQuakeGeneratorClass.cpp
//
// description : C++ source for the EarthQuakeGeneratorClass.
//               A singleton class derived from DeviceClass.
//               It implements the command and attribute list
//               and all properties and methods required
//               by the EarthQuakeGenerator once per process.
//
// project :     EarthQuakeGenerator
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
// Matteo Di Carlo INAF
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <EarthQuakeGeneratorClass.h>

/*----- PROTECTED REGION END -----*/	//	EarthQuakeGeneratorClass.cpp

//-------------------------------------------------------------------
/**
 *	Create EarthQuakeGeneratorClass singleton and
 *	return it in a C function for Python usage
 */
//-------------------------------------------------------------------
extern "C" {
#ifdef _TG_WINDOWS_

__declspec(dllexport)

#endif

	Tango::DeviceClass *_create_EarthQuakeGenerator_class(const char *name) {
		return EarthQuakeGenerator_ns::EarthQuakeGeneratorClass::init(name);
	}
}

namespace EarthQuakeGenerator_ns
{
//===================================================================
//	Initialize pointer for singleton pattern
//===================================================================
EarthQuakeGeneratorClass *EarthQuakeGeneratorClass::_instance = NULL;

//--------------------------------------------------------
/**
 * method : 		EarthQuakeGeneratorClass::EarthQuakeGeneratorClass(string &s)
 * description : 	constructor for the EarthQuakeGeneratorClass
 *
 * @param s	The class name
 */
//--------------------------------------------------------
EarthQuakeGeneratorClass::EarthQuakeGeneratorClass(string &s):Tango::DeviceClass(s)
{
	cout2 << "Entering EarthQuakeGeneratorClass constructor" << endl;
	set_default_property();
	write_class_property();

	/*----- PROTECTED REGION ID(EarthQuakeGeneratorClass::constructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	EarthQuakeGeneratorClass::constructor

	cout2 << "Leaving EarthQuakeGeneratorClass constructor" << endl;
}

//--------------------------------------------------------
/**
 * method : 		EarthQuakeGeneratorClass::~EarthQuakeGeneratorClass()
 * description : 	destructor for the EarthQuakeGeneratorClass
 */
//--------------------------------------------------------
EarthQuakeGeneratorClass::~EarthQuakeGeneratorClass()
{
	/*----- PROTECTED REGION ID(EarthQuakeGeneratorClass::destructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	EarthQuakeGeneratorClass::destructor

	_instance = NULL;
}


//--------------------------------------------------------
/**
 * method : 		EarthQuakeGeneratorClass::init
 * description : 	Create the object if not already done.
 *                  Otherwise, just return a pointer to the object
 *
 * @param	name	The class name
 */
//--------------------------------------------------------
EarthQuakeGeneratorClass *EarthQuakeGeneratorClass::init(const char *name)
{
	if (_instance == NULL)
	{
		try
		{
			string s(name);
			_instance = new EarthQuakeGeneratorClass(s);
		}
		catch (bad_alloc &)
		{
			throw;
		}
	}
	return _instance;
}

//--------------------------------------------------------
/**
 * method : 		EarthQuakeGeneratorClass::instance
 * description : 	Check if object already created,
 *                  and return a pointer to the object
 */
//--------------------------------------------------------
EarthQuakeGeneratorClass *EarthQuakeGeneratorClass::instance()
{
	if (_instance == NULL)
	{
		cerr << "Class is not initialised !!" << endl;
		exit(-1);
	}
	return _instance;
}



//===================================================================
//	Command execution method calls
//===================================================================
//--------------------------------------------------------
/**
 * method : 		NextEventClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *NextEventClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "NextEventClass::execute(): arrived" << endl;
	((static_cast<EarthQuakeGenerator *>(device))->next_event());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		StopClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *StopClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "StopClass::execute(): arrived" << endl;
	((static_cast<EarthQuakeGenerator *>(device))->stop());
	return new CORBA::Any();
}


//===================================================================
//	Properties management
//===================================================================
//--------------------------------------------------------
/**
 *	Method      : EarthQuakeGeneratorClass::get_class_property()
 *	Description : Get the class property for specified name.
 */
//--------------------------------------------------------
Tango::DbDatum EarthQuakeGeneratorClass::get_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_prop.size() ; i++)
		if (cl_prop[i].name == prop_name)
			return cl_prop[i];
	//	if not found, returns  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : EarthQuakeGeneratorClass::get_default_device_property()
 *	Description : Return the default value for device property.
 */
//--------------------------------------------------------
Tango::DbDatum EarthQuakeGeneratorClass::get_default_device_property(string &prop_name)
{
	for (unsigned int i=0 ; i<dev_def_prop.size() ; i++)
		if (dev_def_prop[i].name == prop_name)
			return dev_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : EarthQuakeGeneratorClass::get_default_class_property()
 *	Description : Return the default value for class property.
 */
//--------------------------------------------------------
Tango::DbDatum EarthQuakeGeneratorClass::get_default_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_def_prop.size() ; i++)
		if (cl_def_prop[i].name == prop_name)
			return cl_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}


//--------------------------------------------------------
/**
 *	Method      : EarthQuakeGeneratorClass::set_default_property()
 *	Description : Set default property (class and device) for wizard.
 *                For each property, add to wizard property name and description.
 *                If default value has been set, add it to wizard property and
 *                store it in a DbDatum.
 */
//--------------------------------------------------------
void EarthQuakeGeneratorClass::set_default_property()
{
	string	prop_name;
	string	prop_desc;
	string	prop_def;
	vector<string>	vect_data;

	//	Set Default Class Properties

	//	Set Default device Properties
}

//--------------------------------------------------------
/**
 *	Method      : EarthQuakeGeneratorClass::write_class_property()
 *	Description : Set class description fields as property in database
 */
//--------------------------------------------------------
void EarthQuakeGeneratorClass::write_class_property()
{
	//	First time, check if database used
	if (Tango::Util::_UseDb == false)
		return;

	Tango::DbData	data;
	string	classname = get_name();
	string	header;
	string::size_type	start, end;

	//	Put title
	Tango::DbDatum	title("ProjectTitle");
	string	str_title("EarthQuakeGenerator");
	title << str_title;
	data.push_back(title);

	//	Put Description
	Tango::DbDatum	description("Description");
	vector<string>	str_desc;
	str_desc.push_back("EarthQuakeGenerator");
	description << str_desc;
	data.push_back(description);

	//	put cvs or svn location
	string	filename("EarthQuakeGenerator");
	filename += "Class.cpp";

	// check for cvs information
	string	src_path(CvsPath);
	start = src_path.find("/");
	if (start!=string::npos)
	{
		end   = src_path.find(filename);
		if (end>start)
		{
			string	strloc = src_path.substr(start, end-start);
			//	Check if specific repository
			start = strloc.find("/cvsroot/");
			if (start!=string::npos && start>0)
			{
				string	repository = strloc.substr(0, start);
				if (repository.find("/segfs/")!=string::npos)
					strloc = "ESRF:" + strloc.substr(start, strloc.length()-start);
			}
			Tango::DbDatum	cvs_loc("cvs_location");
			cvs_loc << strloc;
			data.push_back(cvs_loc);
		}
	}

	// check for svn information
	else
	{
		string	src_path(SvnPath);
		start = src_path.find("://");
		if (start!=string::npos)
		{
			end = src_path.find(filename);
			if (end>start)
			{
				header = "$HeadURL: ";
				start = header.length();
				string	strloc = src_path.substr(start, (end-start));
				
				Tango::DbDatum	svn_loc("svn_location");
				svn_loc << strloc;
				data.push_back(svn_loc);
			}
		}
	}

	//	Get CVS or SVN revision tag
	
	// CVS tag
	string	tagname(TagName);
	header = "$Name: ";
	start = header.length();
	string	endstr(" $");
	
	end   = tagname.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strtag = tagname.substr(start, end-start);
		Tango::DbDatum	cvs_tag("cvs_tag");
		cvs_tag << strtag;
		data.push_back(cvs_tag);
	}
	
	// SVN tag
	string	svnpath(SvnPath);
	header = "$HeadURL: ";
	start = header.length();
	
	end   = svnpath.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strloc = svnpath.substr(start, end-start);
		
		string tagstr ("/tags/");
		start = strloc.find(tagstr);
		if ( start!=string::npos )
		{
			start = start + tagstr.length();
			end   = strloc.find(filename);
			string	strtag = strloc.substr(start, end-start-1);
			
			Tango::DbDatum	svn_tag("svn_tag");
			svn_tag << strtag;
			data.push_back(svn_tag);
		}
	}

	//	Get URL location
	string	httpServ(HttpServer);
	if (httpServ.length()>0)
	{
		Tango::DbDatum	db_doc_url("doc_url");
		db_doc_url << httpServ;
		data.push_back(db_doc_url);
	}

	//  Put inheritance
	Tango::DbDatum	inher_datum("InheritedFrom");
	vector<string> inheritance;
	inheritance.push_back("TANGO_BASE_CLASS");
	inher_datum << inheritance;
	data.push_back(inher_datum);

	//	Call database and and values
	get_db_class()->put_property(data);
}

//===================================================================
//	Factory methods
//===================================================================

//--------------------------------------------------------
/**
 *	Method      : EarthQuakeGeneratorClass::device_factory()
 *	Description : Create the device object(s)
 *                and store them in the device list
 */
//--------------------------------------------------------
void EarthQuakeGeneratorClass::device_factory(const Tango::DevVarStringArray *devlist_ptr)
{
	/*----- PROTECTED REGION ID(EarthQuakeGeneratorClass::device_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	EarthQuakeGeneratorClass::device_factory_before

	//	Create devices and add it into the device list
	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		cout4 << "Device name : " << (*devlist_ptr)[i].in() << endl;
		device_list.push_back(new EarthQuakeGenerator(this, (*devlist_ptr)[i]));
	}

	//	Manage dynamic attributes if any
	erase_dynamic_attributes(devlist_ptr, get_class_attr()->get_attr_list());

	//	Export devices to the outside world
	for (unsigned long i=1 ; i<=devlist_ptr->length() ; i++)
	{
		//	Add dynamic attributes if any
		EarthQuakeGenerator *dev = static_cast<EarthQuakeGenerator *>(device_list[device_list.size()-i]);
		dev->add_dynamic_attributes();

		//	Check before if database used.
		if ((Tango::Util::_UseDb == true) && (Tango::Util::_FileDb == false))
			export_device(dev);
		else
			export_device(dev, dev->get_name().c_str());
	}

	/*----- PROTECTED REGION ID(EarthQuakeGeneratorClass::device_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	EarthQuakeGeneratorClass::device_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : EarthQuakeGeneratorClass::attribute_factory()
 *	Description : Create the attribute object(s)
 *                and store them in the attribute list
 */
//--------------------------------------------------------
void EarthQuakeGeneratorClass::attribute_factory(vector<Tango::Attr *> &att_list)
{
	/*----- PROTECTED REGION ID(EarthQuakeGeneratorClass::attribute_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	EarthQuakeGeneratorClass::attribute_factory_before
	//	Attribute : DateReferenceEvent
	DateReferenceEventAttrib	*datereferenceevent = new DateReferenceEventAttrib();
	Tango::UserDefaultAttrProp	datereferenceevent_prop;
	//	description	not set for DateReferenceEvent
	//	label	not set for DateReferenceEvent
	//	unit	not set for DateReferenceEvent
	//	standard_unit	not set for DateReferenceEvent
	//	display_unit	not set for DateReferenceEvent
	//	format	not set for DateReferenceEvent
	//	max_value	not set for DateReferenceEvent
	//	min_value	not set for DateReferenceEvent
	//	max_alarm	not set for DateReferenceEvent
	//	min_alarm	not set for DateReferenceEvent
	//	max_warning	not set for DateReferenceEvent
	//	min_warning	not set for DateReferenceEvent
	//	delta_t	not set for DateReferenceEvent
	//	delta_val	not set for DateReferenceEvent
	
	datereferenceevent->set_default_properties(datereferenceevent_prop);
	//	Not Polled
	datereferenceevent->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	datereferenceevent->set_archive_event(true, true);
	att_list.push_back(datereferenceevent);

	//	Attribute : Latitude
	LatitudeAttrib	*latitude = new LatitudeAttrib();
	Tango::UserDefaultAttrProp	latitude_prop;
	//	description	not set for Latitude
	//	label	not set for Latitude
	//	unit	not set for Latitude
	//	standard_unit	not set for Latitude
	//	display_unit	not set for Latitude
	//	format	not set for Latitude
	//	max_value	not set for Latitude
	//	min_value	not set for Latitude
	//	max_alarm	not set for Latitude
	//	min_alarm	not set for Latitude
	//	max_warning	not set for Latitude
	//	min_warning	not set for Latitude
	//	delta_t	not set for Latitude
	//	delta_val	not set for Latitude
	
	latitude->set_default_properties(latitude_prop);
	//	Not Polled
	latitude->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	latitude->set_archive_event(true, true);
	att_list.push_back(latitude);

	//	Attribute : Longitude
	LongitudeAttrib	*longitude = new LongitudeAttrib();
	Tango::UserDefaultAttrProp	longitude_prop;
	//	description	not set for Longitude
	//	label	not set for Longitude
	//	unit	not set for Longitude
	//	standard_unit	not set for Longitude
	//	display_unit	not set for Longitude
	//	format	not set for Longitude
	//	max_value	not set for Longitude
	//	min_value	not set for Longitude
	//	max_alarm	not set for Longitude
	//	min_alarm	not set for Longitude
	//	max_warning	not set for Longitude
	//	min_warning	not set for Longitude
	//	delta_t	not set for Longitude
	//	delta_val	not set for Longitude
	
	longitude->set_default_properties(longitude_prop);
	//	Not Polled
	longitude->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	longitude->set_archive_event(true, true);
	att_list.push_back(longitude);

	//	Attribute : Depth
	DepthAttrib	*depth = new DepthAttrib();
	Tango::UserDefaultAttrProp	depth_prop;
	//	description	not set for Depth
	//	label	not set for Depth
	//	unit	not set for Depth
	//	standard_unit	not set for Depth
	//	display_unit	not set for Depth
	//	format	not set for Depth
	//	max_value	not set for Depth
	//	min_value	not set for Depth
	//	max_alarm	not set for Depth
	//	min_alarm	not set for Depth
	//	max_warning	not set for Depth
	//	min_warning	not set for Depth
	//	delta_t	not set for Depth
	//	delta_val	not set for Depth
	
	depth->set_default_properties(depth_prop);
	//	Not Polled
	depth->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	depth->set_archive_event(true, true);
	att_list.push_back(depth);

	//	Attribute : ReportedMagnitudes
	ReportedMagnitudesAttrib	*reportedmagnitudes = new ReportedMagnitudesAttrib();
	Tango::UserDefaultAttrProp	reportedmagnitudes_prop;
	//	description	not set for ReportedMagnitudes
	//	label	not set for ReportedMagnitudes
	//	unit	not set for ReportedMagnitudes
	//	standard_unit	not set for ReportedMagnitudes
	//	display_unit	not set for ReportedMagnitudes
	//	format	not set for ReportedMagnitudes
	//	max_value	not set for ReportedMagnitudes
	//	min_value	not set for ReportedMagnitudes
	//	max_alarm	not set for ReportedMagnitudes
	//	min_alarm	not set for ReportedMagnitudes
	//	max_warning	not set for ReportedMagnitudes
	//	min_warning	not set for ReportedMagnitudes
	//	delta_t	not set for ReportedMagnitudes
	//	delta_val	not set for ReportedMagnitudes
	
	reportedmagnitudes->set_default_properties(reportedmagnitudes_prop);
	//	Not Polled
	reportedmagnitudes->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	reportedmagnitudes->set_archive_event(true, true);
	att_list.push_back(reportedmagnitudes);

	//	Attribute : GeographicaLocation
	GeographicaLocationAttrib	*geographicalocation = new GeographicaLocationAttrib();
	Tango::UserDefaultAttrProp	geographicalocation_prop;
	//	description	not set for GeographicaLocation
	//	label	not set for GeographicaLocation
	//	unit	not set for GeographicaLocation
	//	standard_unit	not set for GeographicaLocation
	//	display_unit	not set for GeographicaLocation
	//	format	not set for GeographicaLocation
	//	max_value	not set for GeographicaLocation
	//	min_value	not set for GeographicaLocation
	//	max_alarm	not set for GeographicaLocation
	//	min_alarm	not set for GeographicaLocation
	//	max_warning	not set for GeographicaLocation
	//	min_warning	not set for GeographicaLocation
	//	delta_t	not set for GeographicaLocation
	//	delta_val	not set for GeographicaLocation
	
	geographicalocation->set_default_properties(geographicalocation_prop);
	//	Not Polled
	geographicalocation->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	geographicalocation->set_archive_event(true, true);
	att_list.push_back(geographicalocation);

	//	Attribute : JsonTrans
	JsonTransAttrib	*jsontrans = new JsonTransAttrib();
	Tango::UserDefaultAttrProp	jsontrans_prop;
	//	description	not set for JsonTrans
	//	label	not set for JsonTrans
	//	unit	not set for JsonTrans
	//	standard_unit	not set for JsonTrans
	//	display_unit	not set for JsonTrans
	//	format	not set for JsonTrans
	//	max_value	not set for JsonTrans
	//	min_value	not set for JsonTrans
	//	max_alarm	not set for JsonTrans
	//	min_alarm	not set for JsonTrans
	//	max_warning	not set for JsonTrans
	//	min_warning	not set for JsonTrans
	//	delta_t	not set for JsonTrans
	//	delta_val	not set for JsonTrans
	
	jsontrans->set_default_properties(jsontrans_prop);
	//	Not Polled
	jsontrans->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(jsontrans);

	//	Attribute : NdkFileName
	NdkFileNameAttrib	*ndkfilename = new NdkFileNameAttrib();
	Tango::UserDefaultAttrProp	ndkfilename_prop;
	//	description	not set for NdkFileName
	//	label	not set for NdkFileName
	//	unit	not set for NdkFileName
	//	standard_unit	not set for NdkFileName
	//	display_unit	not set for NdkFileName
	//	format	not set for NdkFileName
	//	max_value	not set for NdkFileName
	//	min_value	not set for NdkFileName
	//	max_alarm	not set for NdkFileName
	//	min_alarm	not set for NdkFileName
	//	max_warning	not set for NdkFileName
	//	min_warning	not set for NdkFileName
	//	delta_t	not set for NdkFileName
	//	delta_val	not set for NdkFileName
	
	ndkfilename->set_default_properties(ndkfilename_prop);
	//	Not Polled
	ndkfilename->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(ndkfilename);

	//	Attribute : archiveValue
	archiveValueAttrib	*archivevalue = new archiveValueAttrib();
	Tango::UserDefaultAttrProp	archivevalue_prop;
	//	description	not set for archiveValue
	//	label	not set for archiveValue
	//	unit	not set for archiveValue
	//	standard_unit	not set for archiveValue
	//	display_unit	not set for archiveValue
	//	format	not set for archiveValue
	//	max_value	not set for archiveValue
	//	min_value	not set for archiveValue
	//	max_alarm	not set for archiveValue
	//	min_alarm	not set for archiveValue
	//	max_warning	not set for archiveValue
	//	min_warning	not set for archiveValue
	//	delta_t	not set for archiveValue
	//	delta_val	not set for archiveValue
	
	archivevalue->set_default_properties(archivevalue_prop);
	archivevalue->set_polling_period(1000);
	archivevalue->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(archivevalue);


	//	Create a list of static attributes
	create_static_attribute_list(get_class_attr()->get_attr_list());
	/*----- PROTECTED REGION ID(EarthQuakeGeneratorClass::attribute_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	EarthQuakeGeneratorClass::attribute_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : EarthQuakeGeneratorClass::pipe_factory()
 *	Description : Create the pipe object(s)
 *                and store them in the pipe list
 */
//--------------------------------------------------------
void EarthQuakeGeneratorClass::pipe_factory()
{
	/*----- PROTECTED REGION ID(EarthQuakeGeneratorClass::pipe_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	EarthQuakeGeneratorClass::pipe_factory_before
	/*----- PROTECTED REGION ID(EarthQuakeGeneratorClass::pipe_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	EarthQuakeGeneratorClass::pipe_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : EarthQuakeGeneratorClass::command_factory()
 *	Description : Create the command object(s)
 *                and store them in the command list
 */
//--------------------------------------------------------
void EarthQuakeGeneratorClass::command_factory()
{
	/*----- PROTECTED REGION ID(EarthQuakeGeneratorClass::command_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	EarthQuakeGeneratorClass::command_factory_before


	//	Command NextEvent
	NextEventClass	*pNextEventCmd =
		new NextEventClass("NextEvent",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pNextEventCmd);

	//	Command Stop
	StopClass	*pStopCmd =
		new StopClass("Stop",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pStopCmd);

	/*----- PROTECTED REGION ID(EarthQuakeGeneratorClass::command_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	EarthQuakeGeneratorClass::command_factory_after
}

//===================================================================
//	Dynamic attributes related methods
//===================================================================

//--------------------------------------------------------
/**
 * method : 		EarthQuakeGeneratorClass::create_static_attribute_list
 * description : 	Create the a list of static attributes
 *
 * @param	att_list	the ceated attribute list
 */
//--------------------------------------------------------
void EarthQuakeGeneratorClass::create_static_attribute_list(vector<Tango::Attr *> &att_list)
{
	for (unsigned long i=0 ; i<att_list.size() ; i++)
	{
		string att_name(att_list[i]->get_name());
		transform(att_name.begin(), att_name.end(), att_name.begin(), ::tolower);
		defaultAttList.push_back(att_name);
	}

	cout2 << defaultAttList.size() << " attributes in default list" << endl;

	/*----- PROTECTED REGION ID(EarthQuakeGeneratorClass::create_static_att_list) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	EarthQuakeGeneratorClass::create_static_att_list
}


//--------------------------------------------------------
/**
 * method : 		EarthQuakeGeneratorClass::erase_dynamic_attributes
 * description : 	delete the dynamic attributes if any.
 *
 * @param	devlist_ptr	the device list pointer
 * @param	list of all attributes
 */
//--------------------------------------------------------
void EarthQuakeGeneratorClass::erase_dynamic_attributes(const Tango::DevVarStringArray *devlist_ptr, vector<Tango::Attr *> &att_list)
{
	Tango::Util *tg = Tango::Util::instance();

	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		Tango::DeviceImpl *dev_impl = tg->get_device_by_name(((string)(*devlist_ptr)[i]).c_str());
		EarthQuakeGenerator *dev = static_cast<EarthQuakeGenerator *> (dev_impl);

		vector<Tango::Attribute *> &dev_att_list = dev->get_device_attr()->get_attribute_list();
		vector<Tango::Attribute *>::iterator ite_att;
		for (ite_att=dev_att_list.begin() ; ite_att != dev_att_list.end() ; ++ite_att)
		{
			string att_name((*ite_att)->get_name_lower());
			if ((att_name == "state") || (att_name == "status"))
				continue;
			vector<string>::iterator ite_str = find(defaultAttList.begin(), defaultAttList.end(), att_name);
			if (ite_str == defaultAttList.end())
			{
				cout2 << att_name << " is a UNWANTED dynamic attribute for device " << (*devlist_ptr)[i] << endl;
				Tango::Attribute &att = dev->get_device_attr()->get_attr_by_name(att_name.c_str());
				dev->remove_attribute(att_list[att.get_attr_idx()], true, false);
				--ite_att;
			}
		}
	}
	/*----- PROTECTED REGION ID(EarthQuakeGeneratorClass::erase_dynamic_attributes) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	EarthQuakeGeneratorClass::erase_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Method      : EarthQuakeGeneratorClass::get_attr_by_name()
 *	Description : returns Tango::Attr * object found by name
 */
//--------------------------------------------------------
Tango::Attr *EarthQuakeGeneratorClass::get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname)
{
	vector<Tango::Attr *>::iterator it;
	for (it=att_list.begin() ; it<att_list.end() ; ++it)
		if ((*it)->get_name()==attname)
			return (*it);
	//	Attr does not exist
	return NULL;
}


/*----- PROTECTED REGION ID(EarthQuakeGeneratorClass::Additional Methods) ENABLED START -----*/

/*----- PROTECTED REGION END -----*/	//	EarthQuakeGeneratorClass::Additional Methods
} //	namespace
