/*----- PROTECTED REGION ID(AmicaLoggerClass.cpp) ENABLED START -----*/
static const char *RcsId      = "$Id:  $";
static const char *TagName    = "$Name:  $";
static const char *CvsPath    = "$Source:  $";
static const char *SvnPath    = "$HeadURL:  $";
static const char *HttpServer = "http://www.esrf.eu/computing/cs/tango/tango_doc/ds_doc/";
//=============================================================================
//
// file :        AmicaLoggerClass.cpp
//
// description : C++ source for the AmicaLoggerClass.
//               A singleton class derived from DeviceClass.
//               It implements the command and attribute list
//               and all properties and methods required
//               by the AmicaLogger once per process.
//
// project :     AmicaLogger
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
// Matteo Di Carlo
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <AmicaLoggerClass.h>

/*----- PROTECTED REGION END -----*/	//	AmicaLoggerClass.cpp

//-------------------------------------------------------------------
/**
 *	Create AmicaLoggerClass singleton and
 *	return it in a C function for Python usage
 */
//-------------------------------------------------------------------
extern "C" {
#ifdef _TG_WINDOWS_

__declspec(dllexport)

#endif

	Tango::DeviceClass *_create_AmicaLogger_class(const char *name) {
		return AmicaLogger_ns::AmicaLoggerClass::init(name);
	}
}

namespace AmicaLogger_ns
{
//===================================================================
//	Initialize pointer for singleton pattern
//===================================================================
AmicaLoggerClass *AmicaLoggerClass::_instance = NULL;

//--------------------------------------------------------
/**
 * method : 		AmicaLoggerClass::AmicaLoggerClass(string &s)
 * description : 	constructor for the AmicaLoggerClass
 *
 * @param s	The class name
 */
//--------------------------------------------------------
AmicaLoggerClass::AmicaLoggerClass(string &s):Tango::DeviceClass(s)
{
	cout2 << "Entering AmicaLoggerClass constructor" << endl;
	set_default_property();
	write_class_property();

	/*----- PROTECTED REGION ID(AmicaLoggerClass::constructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	AmicaLoggerClass::constructor

	cout2 << "Leaving AmicaLoggerClass constructor" << endl;
}

//--------------------------------------------------------
/**
 * method : 		AmicaLoggerClass::~AmicaLoggerClass()
 * description : 	destructor for the AmicaLoggerClass
 */
//--------------------------------------------------------
AmicaLoggerClass::~AmicaLoggerClass()
{
	/*----- PROTECTED REGION ID(AmicaLoggerClass::destructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	AmicaLoggerClass::destructor

	_instance = NULL;
}


//--------------------------------------------------------
/**
 * method : 		AmicaLoggerClass::init
 * description : 	Create the object if not already done.
 *                  Otherwise, just return a pointer to the object
 *
 * @param	name	The class name
 */
//--------------------------------------------------------
AmicaLoggerClass *AmicaLoggerClass::init(const char *name)
{
	if (_instance == NULL)
	{
		try
		{
			string s(name);
			_instance = new AmicaLoggerClass(s);
		}
		catch (bad_alloc &)
		{
			throw;
		}
	}
	return _instance;
}

//--------------------------------------------------------
/**
 * method : 		AmicaLoggerClass::instance
 * description : 	Check if object already created,
 *                  and return a pointer to the object
 */
//--------------------------------------------------------
AmicaLoggerClass *AmicaLoggerClass::instance()
{
	if (_instance == NULL)
	{
		cerr << "Class is not initialised !!" << endl;
		exit(-1);
	}
	return _instance;
}



//===================================================================
//	Command execution method calls
//===================================================================
//--------------------------------------------------------
/**
 * method : 		NextClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *NextClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "NextClass::execute(): arrived" << endl;
	((static_cast<AmicaLogger *>(device))->next());
	return new CORBA::Any();
}


//===================================================================
//	Properties management
//===================================================================
//--------------------------------------------------------
/**
 *	Method      : AmicaLoggerClass::get_class_property()
 *	Description : Get the class property for specified name.
 */
//--------------------------------------------------------
Tango::DbDatum AmicaLoggerClass::get_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_prop.size() ; i++)
		if (cl_prop[i].name == prop_name)
			return cl_prop[i];
	//	if not found, returns  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : AmicaLoggerClass::get_default_device_property()
 *	Description : Return the default value for device property.
 */
//--------------------------------------------------------
Tango::DbDatum AmicaLoggerClass::get_default_device_property(string &prop_name)
{
	for (unsigned int i=0 ; i<dev_def_prop.size() ; i++)
		if (dev_def_prop[i].name == prop_name)
			return dev_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : AmicaLoggerClass::get_default_class_property()
 *	Description : Return the default value for class property.
 */
//--------------------------------------------------------
Tango::DbDatum AmicaLoggerClass::get_default_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_def_prop.size() ; i++)
		if (cl_def_prop[i].name == prop_name)
			return cl_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}


//--------------------------------------------------------
/**
 *	Method      : AmicaLoggerClass::set_default_property()
 *	Description : Set default property (class and device) for wizard.
 *                For each property, add to wizard property name and description.
 *                If default value has been set, add it to wizard property and
 *                store it in a DbDatum.
 */
//--------------------------------------------------------
void AmicaLoggerClass::set_default_property()
{
	string	prop_name;
	string	prop_desc;
	string	prop_def;
	vector<string>	vect_data;

	//	Set Default Class Properties

	//	Set Default device Properties
}

//--------------------------------------------------------
/**
 *	Method      : AmicaLoggerClass::write_class_property()
 *	Description : Set class description fields as property in database
 */
//--------------------------------------------------------
void AmicaLoggerClass::write_class_property()
{
	//	First time, check if database used
	if (Tango::Util::_UseDb == false)
		return;

	Tango::DbData	data;
	string	classname = get_name();
	string	header;
	string::size_type	start, end;

	//	Put title
	Tango::DbDatum	title("ProjectTitle");
	string	str_title("AmicaLogger");
	title << str_title;
	data.push_back(title);

	//	Put Description
	Tango::DbDatum	description("Description");
	vector<string>	str_desc;
	str_desc.push_back("AmicaLogger");
	description << str_desc;
	data.push_back(description);

	//	put cvs or svn location
	string	filename("AmicaLogger");
	filename += "Class.cpp";

	// check for cvs information
	string	src_path(CvsPath);
	start = src_path.find("/");
	if (start!=string::npos)
	{
		end   = src_path.find(filename);
		if (end>start)
		{
			string	strloc = src_path.substr(start, end-start);
			//	Check if specific repository
			start = strloc.find("/cvsroot/");
			if (start!=string::npos && start>0)
			{
				string	repository = strloc.substr(0, start);
				if (repository.find("/segfs/")!=string::npos)
					strloc = "ESRF:" + strloc.substr(start, strloc.length()-start);
			}
			Tango::DbDatum	cvs_loc("cvs_location");
			cvs_loc << strloc;
			data.push_back(cvs_loc);
		}
	}

	// check for svn information
	else
	{
		string	src_path(SvnPath);
		start = src_path.find("://");
		if (start!=string::npos)
		{
			end = src_path.find(filename);
			if (end>start)
			{
				header = "$HeadURL: ";
				start = header.length();
				string	strloc = src_path.substr(start, (end-start));
				
				Tango::DbDatum	svn_loc("svn_location");
				svn_loc << strloc;
				data.push_back(svn_loc);
			}
		}
	}

	//	Get CVS or SVN revision tag
	
	// CVS tag
	string	tagname(TagName);
	header = "$Name: ";
	start = header.length();
	string	endstr(" $");
	
	end   = tagname.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strtag = tagname.substr(start, end-start);
		Tango::DbDatum	cvs_tag("cvs_tag");
		cvs_tag << strtag;
		data.push_back(cvs_tag);
	}
	
	// SVN tag
	string	svnpath(SvnPath);
	header = "$HeadURL: ";
	start = header.length();
	
	end   = svnpath.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strloc = svnpath.substr(start, end-start);
		
		string tagstr ("/tags/");
		start = strloc.find(tagstr);
		if ( start!=string::npos )
		{
			start = start + tagstr.length();
			end   = strloc.find(filename);
			string	strtag = strloc.substr(start, end-start-1);
			
			Tango::DbDatum	svn_tag("svn_tag");
			svn_tag << strtag;
			data.push_back(svn_tag);
		}
	}

	//	Get URL location
	string	httpServ(HttpServer);
	if (httpServ.length()>0)
	{
		Tango::DbDatum	db_doc_url("doc_url");
		db_doc_url << httpServ;
		data.push_back(db_doc_url);
	}

	//  Put inheritance
	Tango::DbDatum	inher_datum("InheritedFrom");
	vector<string> inheritance;
	inheritance.push_back("TANGO_BASE_CLASS");
	inher_datum << inheritance;
	data.push_back(inher_datum);

	//	Call database and and values
	get_db_class()->put_property(data);
}

//===================================================================
//	Factory methods
//===================================================================

//--------------------------------------------------------
/**
 *	Method      : AmicaLoggerClass::device_factory()
 *	Description : Create the device object(s)
 *                and store them in the device list
 */
//--------------------------------------------------------
void AmicaLoggerClass::device_factory(const Tango::DevVarStringArray *devlist_ptr)
{
	/*----- PROTECTED REGION ID(AmicaLoggerClass::device_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	AmicaLoggerClass::device_factory_before

	//	Create devices and add it into the device list
	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		cout4 << "Device name : " << (*devlist_ptr)[i].in() << endl;
		device_list.push_back(new AmicaLogger(this, (*devlist_ptr)[i]));
	}

	//	Manage dynamic attributes if any
	erase_dynamic_attributes(devlist_ptr, get_class_attr()->get_attr_list());

	//	Export devices to the outside world
	for (unsigned long i=1 ; i<=devlist_ptr->length() ; i++)
	{
		//	Add dynamic attributes if any
		AmicaLogger *dev = static_cast<AmicaLogger *>(device_list[device_list.size()-i]);
		dev->add_dynamic_attributes();

		//	Check before if database used.
		if ((Tango::Util::_UseDb == true) && (Tango::Util::_FileDb == false))
			export_device(dev);
		else
			export_device(dev, dev->get_name().c_str());
	}

	/*----- PROTECTED REGION ID(AmicaLoggerClass::device_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	AmicaLoggerClass::device_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : AmicaLoggerClass::attribute_factory()
 *	Description : Create the attribute object(s)
 *                and store them in the attribute list
 */
//--------------------------------------------------------
void AmicaLoggerClass::attribute_factory(vector<Tango::Attr *> &att_list)
{
	/*----- PROTECTED REGION ID(AmicaLoggerClass::attribute_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	AmicaLoggerClass::attribute_factory_before
	//	Attribute : ActivePower1
	ActivePower1Attrib	*activepower1 = new ActivePower1Attrib();
	Tango::UserDefaultAttrProp	activepower1_prop;
	//	description	not set for ActivePower1
	activepower1_prop.set_label("Potenza attiva (trifase)");
	activepower1_prop.set_unit("Watt");
	//	standard_unit	not set for ActivePower1
	//	display_unit	not set for ActivePower1
	//	format	not set for ActivePower1
	//	max_value	not set for ActivePower1
	//	min_value	not set for ActivePower1
	//	max_alarm	not set for ActivePower1
	//	min_alarm	not set for ActivePower1
	//	max_warning	not set for ActivePower1
	//	min_warning	not set for ActivePower1
	//	delta_t	not set for ActivePower1
	//	delta_val	not set for ActivePower1
	
	activepower1->set_default_properties(activepower1_prop);
	//	Not Polled
	activepower1->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	activepower1->set_archive_event(true, true);
	att_list.push_back(activepower1);

	//	Attribute : ActivePower2
	ActivePower2Attrib	*activepower2 = new ActivePower2Attrib();
	Tango::UserDefaultAttrProp	activepower2_prop;
	//	description	not set for ActivePower2
	activepower2_prop.set_label("Potenza attiva (trifase)");
	activepower2_prop.set_unit("Watt");
	//	standard_unit	not set for ActivePower2
	//	display_unit	not set for ActivePower2
	//	format	not set for ActivePower2
	//	max_value	not set for ActivePower2
	//	min_value	not set for ActivePower2
	//	max_alarm	not set for ActivePower2
	//	min_alarm	not set for ActivePower2
	//	max_warning	not set for ActivePower2
	//	min_warning	not set for ActivePower2
	//	delta_t	not set for ActivePower2
	//	delta_val	not set for ActivePower2
	
	activepower2->set_default_properties(activepower2_prop);
	//	Not Polled
	activepower2->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	activepower2->set_archive_event(true, true);
	att_list.push_back(activepower2);

	//	Attribute : ActivePower3
	ActivePower3Attrib	*activepower3 = new ActivePower3Attrib();
	Tango::UserDefaultAttrProp	activepower3_prop;
	//	description	not set for ActivePower3
	activepower3_prop.set_label("Potenza attiva (trifase)");
	activepower3_prop.set_unit("Watt");
	//	standard_unit	not set for ActivePower3
	//	display_unit	not set for ActivePower3
	//	format	not set for ActivePower3
	//	max_value	not set for ActivePower3
	//	min_value	not set for ActivePower3
	//	max_alarm	not set for ActivePower3
	//	min_alarm	not set for ActivePower3
	//	max_warning	not set for ActivePower3
	//	min_warning	not set for ActivePower3
	//	delta_t	not set for ActivePower3
	//	delta_val	not set for ActivePower3
	
	activepower3->set_default_properties(activepower3_prop);
	//	Not Polled
	activepower3->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	activepower3->set_archive_event(true, true);
	att_list.push_back(activepower3);

	//	Attribute : CurrentVoltage1
	CurrentVoltage1Attrib	*currentvoltage1 = new CurrentVoltage1Attrib();
	Tango::UserDefaultAttrProp	currentvoltage1_prop;
	//	description	not set for CurrentVoltage1
	currentvoltage1_prop.set_label("Corrente di linea (trifase)");
	currentvoltage1_prop.set_unit("milliAmpere");
	//	standard_unit	not set for CurrentVoltage1
	//	display_unit	not set for CurrentVoltage1
	//	format	not set for CurrentVoltage1
	//	max_value	not set for CurrentVoltage1
	//	min_value	not set for CurrentVoltage1
	//	max_alarm	not set for CurrentVoltage1
	//	min_alarm	not set for CurrentVoltage1
	//	max_warning	not set for CurrentVoltage1
	//	min_warning	not set for CurrentVoltage1
	//	delta_t	not set for CurrentVoltage1
	//	delta_val	not set for CurrentVoltage1
	
	currentvoltage1->set_default_properties(currentvoltage1_prop);
	//	Not Polled
	currentvoltage1->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	currentvoltage1->set_archive_event(true, true);
	att_list.push_back(currentvoltage1);

	//	Attribute : CurrentVoltage2
	CurrentVoltage2Attrib	*currentvoltage2 = new CurrentVoltage2Attrib();
	Tango::UserDefaultAttrProp	currentvoltage2_prop;
	//	description	not set for CurrentVoltage2
	currentvoltage2_prop.set_label("Corrente di linea (trifase)");
	currentvoltage2_prop.set_unit("milliAmpere");
	//	standard_unit	not set for CurrentVoltage2
	//	display_unit	not set for CurrentVoltage2
	//	format	not set for CurrentVoltage2
	//	max_value	not set for CurrentVoltage2
	//	min_value	not set for CurrentVoltage2
	//	max_alarm	not set for CurrentVoltage2
	//	min_alarm	not set for CurrentVoltage2
	//	max_warning	not set for CurrentVoltage2
	//	min_warning	not set for CurrentVoltage2
	//	delta_t	not set for CurrentVoltage2
	//	delta_val	not set for CurrentVoltage2
	
	currentvoltage2->set_default_properties(currentvoltage2_prop);
	//	Not Polled
	currentvoltage2->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	currentvoltage2->set_archive_event(true, true);
	att_list.push_back(currentvoltage2);

	//	Attribute : CurrentVoltage3
	CurrentVoltage3Attrib	*currentvoltage3 = new CurrentVoltage3Attrib();
	Tango::UserDefaultAttrProp	currentvoltage3_prop;
	//	description	not set for CurrentVoltage3
	currentvoltage3_prop.set_label("Corrente di linea (trifase)");
	currentvoltage3_prop.set_unit("milliAmpere");
	//	standard_unit	not set for CurrentVoltage3
	//	display_unit	not set for CurrentVoltage3
	//	format	not set for CurrentVoltage3
	//	max_value	not set for CurrentVoltage3
	//	min_value	not set for CurrentVoltage3
	//	max_alarm	not set for CurrentVoltage3
	//	min_alarm	not set for CurrentVoltage3
	//	max_warning	not set for CurrentVoltage3
	//	min_warning	not set for CurrentVoltage3
	//	delta_t	not set for CurrentVoltage3
	//	delta_val	not set for CurrentVoltage3
	
	currentvoltage3->set_default_properties(currentvoltage3_prop);
	//	Not Polled
	currentvoltage3->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	currentvoltage3->set_archive_event(true, true);
	att_list.push_back(currentvoltage3);

	//	Attribute : Day
	DayAttrib	*day = new DayAttrib();
	Tango::UserDefaultAttrProp	day_prop;
	//	description	not set for Day
	//	label	not set for Day
	//	unit	not set for Day
	//	standard_unit	not set for Day
	//	display_unit	not set for Day
	//	format	not set for Day
	//	max_value	not set for Day
	//	min_value	not set for Day
	//	max_alarm	not set for Day
	//	min_alarm	not set for Day
	//	max_warning	not set for Day
	//	min_warning	not set for Day
	//	delta_t	not set for Day
	//	delta_val	not set for Day
	
	day->set_default_properties(day_prop);
	//	Not Polled
	day->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	day->set_archive_event(true, true);
	att_list.push_back(day);

	//	Attribute : Hour
	HourAttrib	*hour = new HourAttrib();
	Tango::UserDefaultAttrProp	hour_prop;
	//	description	not set for Hour
	//	label	not set for Hour
	//	unit	not set for Hour
	//	standard_unit	not set for Hour
	//	display_unit	not set for Hour
	//	format	not set for Hour
	//	max_value	not set for Hour
	//	min_value	not set for Hour
	//	max_alarm	not set for Hour
	//	min_alarm	not set for Hour
	//	max_warning	not set for Hour
	//	min_warning	not set for Hour
	//	delta_t	not set for Hour
	//	delta_val	not set for Hour
	
	hour->set_default_properties(hour_prop);
	//	Not Polled
	hour->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	hour->set_archive_event(true, true);
	att_list.push_back(hour);

	//	Attribute : LineVoltage1
	LineVoltage1Attrib	*linevoltage1 = new LineVoltage1Attrib();
	Tango::UserDefaultAttrProp	linevoltage1_prop;
	//	description	not set for LineVoltage1
	linevoltage1_prop.set_label("Tensione di linea (trifase)");
	linevoltage1_prop.set_unit("Volt");
	//	standard_unit	not set for LineVoltage1
	//	display_unit	not set for LineVoltage1
	//	format	not set for LineVoltage1
	//	max_value	not set for LineVoltage1
	//	min_value	not set for LineVoltage1
	//	max_alarm	not set for LineVoltage1
	//	min_alarm	not set for LineVoltage1
	//	max_warning	not set for LineVoltage1
	//	min_warning	not set for LineVoltage1
	//	delta_t	not set for LineVoltage1
	//	delta_val	not set for LineVoltage1
	
	linevoltage1->set_default_properties(linevoltage1_prop);
	//	Not Polled
	linevoltage1->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	linevoltage1->set_archive_event(true, true);
	att_list.push_back(linevoltage1);

	//	Attribute : LineVoltage2
	LineVoltage2Attrib	*linevoltage2 = new LineVoltage2Attrib();
	Tango::UserDefaultAttrProp	linevoltage2_prop;
	//	description	not set for LineVoltage2
	linevoltage2_prop.set_label("Tensione di linea (trifase)");
	linevoltage2_prop.set_unit("Volt");
	//	standard_unit	not set for LineVoltage2
	//	display_unit	not set for LineVoltage2
	//	format	not set for LineVoltage2
	//	max_value	not set for LineVoltage2
	//	min_value	not set for LineVoltage2
	//	max_alarm	not set for LineVoltage2
	//	min_alarm	not set for LineVoltage2
	//	max_warning	not set for LineVoltage2
	//	min_warning	not set for LineVoltage2
	//	delta_t	not set for LineVoltage2
	//	delta_val	not set for LineVoltage2
	
	linevoltage2->set_default_properties(linevoltage2_prop);
	//	Not Polled
	linevoltage2->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	linevoltage2->set_archive_event(true, true);
	att_list.push_back(linevoltage2);

	//	Attribute : LineVoltage3
	LineVoltage3Attrib	*linevoltage3 = new LineVoltage3Attrib();
	Tango::UserDefaultAttrProp	linevoltage3_prop;
	//	description	not set for LineVoltage3
	linevoltage3_prop.set_label("Tensione di linea (trifase)");
	linevoltage3_prop.set_unit("Volt");
	//	standard_unit	not set for LineVoltage3
	//	display_unit	not set for LineVoltage3
	//	format	not set for LineVoltage3
	//	max_value	not set for LineVoltage3
	//	min_value	not set for LineVoltage3
	//	max_alarm	not set for LineVoltage3
	//	min_alarm	not set for LineVoltage3
	//	max_warning	not set for LineVoltage3
	//	min_warning	not set for LineVoltage3
	//	delta_t	not set for LineVoltage3
	//	delta_val	not set for LineVoltage3
	
	linevoltage3->set_default_properties(linevoltage3_prop);
	//	Not Polled
	linevoltage3->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(linevoltage3);

	//	Attribute : CurrentNeutro
	CurrentNeutroAttrib	*currentneutro = new CurrentNeutroAttrib();
	Tango::UserDefaultAttrProp	currentneutro_prop;
	//	description	not set for CurrentNeutro
	currentneutro_prop.set_label("Corrente di linea (trifase)");
	currentneutro_prop.set_unit("milliAmpere");
	//	standard_unit	not set for CurrentNeutro
	//	display_unit	not set for CurrentNeutro
	//	format	not set for CurrentNeutro
	//	max_value	not set for CurrentNeutro
	//	min_value	not set for CurrentNeutro
	//	max_alarm	not set for CurrentNeutro
	//	min_alarm	not set for CurrentNeutro
	//	max_warning	not set for CurrentNeutro
	//	min_warning	not set for CurrentNeutro
	//	delta_t	not set for CurrentNeutro
	//	delta_val	not set for CurrentNeutro
	
	currentneutro->set_default_properties(currentneutro_prop);
	//	Not Polled
	currentneutro->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	currentneutro->set_archive_event(true, true);
	att_list.push_back(currentneutro);

	//	Attribute : JsonTrans
	JsonTransAttrib	*jsontrans = new JsonTransAttrib();
	Tango::UserDefaultAttrProp	jsontrans_prop;
	//	description	not set for JsonTrans
	//	label	not set for JsonTrans
	//	unit	not set for JsonTrans
	//	standard_unit	not set for JsonTrans
	//	display_unit	not set for JsonTrans
	//	format	not set for JsonTrans
	//	max_value	not set for JsonTrans
	//	min_value	not set for JsonTrans
	//	max_alarm	not set for JsonTrans
	//	min_alarm	not set for JsonTrans
	//	max_warning	not set for JsonTrans
	//	min_warning	not set for JsonTrans
	//	delta_t	not set for JsonTrans
	//	delta_val	not set for JsonTrans
	
	jsontrans->set_default_properties(jsontrans_prop);
	//	Not Polled
	jsontrans->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	jsontrans->set_archive_event(true, false);
	att_list.push_back(jsontrans);


	//	Create a list of static attributes
	create_static_attribute_list(get_class_attr()->get_attr_list());
	/*----- PROTECTED REGION ID(AmicaLoggerClass::attribute_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	AmicaLoggerClass::attribute_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : AmicaLoggerClass::pipe_factory()
 *	Description : Create the pipe object(s)
 *                and store them in the pipe list
 */
//--------------------------------------------------------
void AmicaLoggerClass::pipe_factory()
{
	/*----- PROTECTED REGION ID(AmicaLoggerClass::pipe_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	AmicaLoggerClass::pipe_factory_before
	/*----- PROTECTED REGION ID(AmicaLoggerClass::pipe_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	AmicaLoggerClass::pipe_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : AmicaLoggerClass::command_factory()
 *	Description : Create the command object(s)
 *                and store them in the command list
 */
//--------------------------------------------------------
void AmicaLoggerClass::command_factory()
{
	/*----- PROTECTED REGION ID(AmicaLoggerClass::command_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	AmicaLoggerClass::command_factory_before


	//	Command Next
	NextClass	*pNextCmd =
		new NextClass("Next",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pNextCmd);

	/*----- PROTECTED REGION ID(AmicaLoggerClass::command_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	AmicaLoggerClass::command_factory_after
}

//===================================================================
//	Dynamic attributes related methods
//===================================================================

//--------------------------------------------------------
/**
 * method : 		AmicaLoggerClass::create_static_attribute_list
 * description : 	Create the a list of static attributes
 *
 * @param	att_list	the ceated attribute list
 */
//--------------------------------------------------------
void AmicaLoggerClass::create_static_attribute_list(vector<Tango::Attr *> &att_list)
{
	for (unsigned long i=0 ; i<att_list.size() ; i++)
	{
		string att_name(att_list[i]->get_name());
		transform(att_name.begin(), att_name.end(), att_name.begin(), ::tolower);
		defaultAttList.push_back(att_name);
	}

	cout2 << defaultAttList.size() << " attributes in default list" << endl;

	/*----- PROTECTED REGION ID(AmicaLoggerClass::create_static_att_list) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	AmicaLoggerClass::create_static_att_list
}


//--------------------------------------------------------
/**
 * method : 		AmicaLoggerClass::erase_dynamic_attributes
 * description : 	delete the dynamic attributes if any.
 *
 * @param	devlist_ptr	the device list pointer
 * @param	list of all attributes
 */
//--------------------------------------------------------
void AmicaLoggerClass::erase_dynamic_attributes(const Tango::DevVarStringArray *devlist_ptr, vector<Tango::Attr *> &att_list)
{
	Tango::Util *tg = Tango::Util::instance();

	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		Tango::DeviceImpl *dev_impl = tg->get_device_by_name(((string)(*devlist_ptr)[i]).c_str());
		AmicaLogger *dev = static_cast<AmicaLogger *> (dev_impl);

		vector<Tango::Attribute *> &dev_att_list = dev->get_device_attr()->get_attribute_list();
		vector<Tango::Attribute *>::iterator ite_att;
		for (ite_att=dev_att_list.begin() ; ite_att != dev_att_list.end() ; ++ite_att)
		{
			string att_name((*ite_att)->get_name_lower());
			if ((att_name == "state") || (att_name == "status"))
				continue;
			vector<string>::iterator ite_str = find(defaultAttList.begin(), defaultAttList.end(), att_name);
			if (ite_str == defaultAttList.end())
			{
				cout2 << att_name << " is a UNWANTED dynamic attribute for device " << (*devlist_ptr)[i] << endl;
				Tango::Attribute &att = dev->get_device_attr()->get_attr_by_name(att_name.c_str());
				dev->remove_attribute(att_list[att.get_attr_idx()], true, false);
				--ite_att;
			}
		}
	}
	/*----- PROTECTED REGION ID(AmicaLoggerClass::erase_dynamic_attributes) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	AmicaLoggerClass::erase_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Method      : AmicaLoggerClass::get_attr_by_name()
 *	Description : returns Tango::Attr * object found by name
 */
//--------------------------------------------------------
Tango::Attr *AmicaLoggerClass::get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname)
{
	vector<Tango::Attr *>::iterator it;
	for (it=att_list.begin() ; it<att_list.end() ; ++it)
		if ((*it)->get_name()==attname)
			return (*it);
	//	Attr does not exist
	return NULL;
}


/*----- PROTECTED REGION ID(AmicaLoggerClass::Additional Methods) ENABLED START -----*/

/*----- PROTECTED REGION END -----*/	//	AmicaLoggerClass::Additional Methods
} //	namespace
