/*----- PROTECTED REGION ID(AmicaLoggerStateMachine.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        AmicaLoggerStateMachine.cpp
//
// description : State machine file for the AmicaLogger class
//
// project :     AmicaLogger
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
// Matteo Di Carlo
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <AmicaLogger.h>

/*----- PROTECTED REGION END -----*/	//	AmicaLogger::AmicaLoggerStateMachine.cpp

//================================================================
//  States  |  Description
//================================================================


namespace AmicaLogger_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : AmicaLogger::is_ActivePower1_allowed()
 *	Description : Execution allowed for ActivePower1 attribute
 */
//--------------------------------------------------------
bool AmicaLogger::is_ActivePower1_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for ActivePower1 attribute in read access.
	/*----- PROTECTED REGION ID(AmicaLogger::ActivePower1StateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	AmicaLogger::ActivePower1StateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : AmicaLogger::is_ActivePower2_allowed()
 *	Description : Execution allowed for ActivePower2 attribute
 */
//--------------------------------------------------------
bool AmicaLogger::is_ActivePower2_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for ActivePower2 attribute in read access.
	/*----- PROTECTED REGION ID(AmicaLogger::ActivePower2StateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	AmicaLogger::ActivePower2StateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : AmicaLogger::is_ActivePower3_allowed()
 *	Description : Execution allowed for ActivePower3 attribute
 */
//--------------------------------------------------------
bool AmicaLogger::is_ActivePower3_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for ActivePower3 attribute in read access.
	/*----- PROTECTED REGION ID(AmicaLogger::ActivePower3StateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	AmicaLogger::ActivePower3StateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : AmicaLogger::is_CurrentVoltage1_allowed()
 *	Description : Execution allowed for CurrentVoltage1 attribute
 */
//--------------------------------------------------------
bool AmicaLogger::is_CurrentVoltage1_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for CurrentVoltage1 attribute in read access.
	/*----- PROTECTED REGION ID(AmicaLogger::CurrentVoltage1StateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	AmicaLogger::CurrentVoltage1StateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : AmicaLogger::is_CurrentVoltage2_allowed()
 *	Description : Execution allowed for CurrentVoltage2 attribute
 */
//--------------------------------------------------------
bool AmicaLogger::is_CurrentVoltage2_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for CurrentVoltage2 attribute in read access.
	/*----- PROTECTED REGION ID(AmicaLogger::CurrentVoltage2StateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	AmicaLogger::CurrentVoltage2StateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : AmicaLogger::is_CurrentVoltage3_allowed()
 *	Description : Execution allowed for CurrentVoltage3 attribute
 */
//--------------------------------------------------------
bool AmicaLogger::is_CurrentVoltage3_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for CurrentVoltage3 attribute in read access.
	/*----- PROTECTED REGION ID(AmicaLogger::CurrentVoltage3StateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	AmicaLogger::CurrentVoltage3StateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : AmicaLogger::is_Day_allowed()
 *	Description : Execution allowed for Day attribute
 */
//--------------------------------------------------------
bool AmicaLogger::is_Day_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for Day attribute in read access.
	/*----- PROTECTED REGION ID(AmicaLogger::DayStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	AmicaLogger::DayStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : AmicaLogger::is_Hour_allowed()
 *	Description : Execution allowed for Hour attribute
 */
//--------------------------------------------------------
bool AmicaLogger::is_Hour_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for Hour attribute in read access.
	/*----- PROTECTED REGION ID(AmicaLogger::HourStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	AmicaLogger::HourStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : AmicaLogger::is_LineVoltage1_allowed()
 *	Description : Execution allowed for LineVoltage1 attribute
 */
//--------------------------------------------------------
bool AmicaLogger::is_LineVoltage1_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for LineVoltage1 attribute in read access.
	/*----- PROTECTED REGION ID(AmicaLogger::LineVoltage1StateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	AmicaLogger::LineVoltage1StateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : AmicaLogger::is_LineVoltage2_allowed()
 *	Description : Execution allowed for LineVoltage2 attribute
 */
//--------------------------------------------------------
bool AmicaLogger::is_LineVoltage2_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for LineVoltage2 attribute in read access.
	/*----- PROTECTED REGION ID(AmicaLogger::LineVoltage2StateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	AmicaLogger::LineVoltage2StateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : AmicaLogger::is_LineVoltage3_allowed()
 *	Description : Execution allowed for LineVoltage3 attribute
 */
//--------------------------------------------------------
bool AmicaLogger::is_LineVoltage3_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for LineVoltage3 attribute in read access.
	/*----- PROTECTED REGION ID(AmicaLogger::LineVoltage3StateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	AmicaLogger::LineVoltage3StateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : AmicaLogger::is_CurrentNeutro_allowed()
 *	Description : Execution allowed for CurrentNeutro attribute
 */
//--------------------------------------------------------
bool AmicaLogger::is_CurrentNeutro_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for CurrentNeutro attribute in read access.
	/*----- PROTECTED REGION ID(AmicaLogger::CurrentNeutroStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	AmicaLogger::CurrentNeutroStateAllowed_READ
	return true;
}


//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : AmicaLogger::is_Next_allowed()
 *	Description : Execution allowed for Next attribute
 */
//--------------------------------------------------------
bool AmicaLogger::is_Next_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Next command.
	/*----- PROTECTED REGION ID(AmicaLogger::NextStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	AmicaLogger::NextStateAllowed
	return true;
}


/*----- PROTECTED REGION ID(AmicaLogger::AmicaLoggerStateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	AmicaLogger::AmicaLoggerStateAllowed.AdditionalMethods

}	//	End of namespace
